# Generated by Django 4.1.7 on 2023-03-29 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_alter_collection_featured_product_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="membership",
            field=models.CharField(
                blank=True,
                choices=[("B", "Bronze"), ("S", "Silver"), ("G", "Gold")],
                default="B",
                max_length=1,
                null=True,
            ),
        ),
    ]
